global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: core-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['core-api:8091']
        labels:
          application: core-api
          env: docker

  - job_name: web-api
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['web-api:8081']
        labels:
          application: web-api
          env: docker
